// Iteration 7: Statistik (läuft nach extras.mjs – dort wurde u. a. „Der Schatten des Windes“ als 2024 gelesen, 5 Sterne importiert)
const base = 'http://localhost:3999/api';
let ok = 0, fail = 0;
const check = (n, c, x = '') => { c ? ok++ : (fail++, console.log('✗', n, x)); };
let cookie = '';
const req = async (m, u, b) => {
  const r = await fetch(base + u, { method: m, headers: { ...(m !== 'GET' ? { 'Content-Type': 'application/json' } : {}), cookie }, body: m !== 'GET' ? JSON.stringify(b ?? {}) : undefined });
  const sc = r.headers.get('set-cookie'); if (sc) cookie = sc.split(';')[0];
  return { status: r.status, data: await r.json().catch(() => null) };
};
await req('POST', '/login', { username: 'simon', password: 'geheim1234' });
let s = (await req('GET', '/stats?year=2024')).data;
check('years list', s.years.includes('2024'));
check('2024 totals', s.totals.books >= 1 && s.totals.pages >= 0 && s.totals.avgRating === 5, JSON.stringify(s.totals));
check('per month march', s.perMonth[2].books >= 1 && s.perMonth.length === 12);
check('ratings dist', s.ratings.find(r => r.rating === 5).n >= 1 && s.ratings.length === 10);
check('highlights', s.highlights.first && s.highlights.fiveStars.length >= 1);
check('formats', s.formats.every(f => ['print', 'ebook', 'none'].includes(f.name)));
check('generic genres filtered', s.genres.every(g => !/^(belletristik|fiction)$/i.test(g.name)), JSON.stringify(s.genres));
const bid = s.perMonth[2].ids[0];
check('month ids + books map', bid && s.books[bid]?.title, JSON.stringify(s.perMonth[2]));
check('languages with ids', s.languages.length >= 1 && s.languages.every(l => l.ids.length === l.n), JSON.stringify(s.languages));
check('page buckets cover all', s.pageBuckets.reduce((a, b) => a + b.n, 0) === s.totals.books);
const old = (await req('GET', `/books/${bid}/reviews`)).data;
const mine = old.reviews?.find?.(r => r.mine) ?? old.mine ?? null;
const put = await req('PUT', `/books/${bid}/review`, { rating: mine?.rating ?? 5, text: mine?.text ?? '', visibility: mine?.visibility ?? 'private', spoiler: mine?.spoiler, moods: ['dark', 'tense', 'bogus'], pace: 'fast' });
check('review moods saved', put.status === 200 && JSON.stringify(put.data).includes('"moods":["dark","tense"]'), JSON.stringify(put.data).slice(0, 300));
s = (await req('GET', '/stats?year=2024')).data;
check('moods stats', s.moods.some(m => m.name === 'dark' && m.ids.includes(bid)) && s.paces[0]?.name === 'fast', JSON.stringify(s.moods));
check('mood map', s.perMonth[2].mood === -1 && s.perMonth[11].mood === -1 && s.perMonth[0].mood === null, JSON.stringify(s.perMonth.map(m => m.mood)));
await req('PATCH', '/me', { prefs: { reviewVisibility: 'private' } });
check('review visibility pref', (await req('GET', '/me')).data.prefs.reviewVisibility === 'private');
await req('PATCH', '/me', { prefs: { reviewVisibility: 'nonsense' } });
check('bad pref ignored', (await req('GET', '/me')).data.prefs.reviewVisibility === 'private');
check('imprint bad url 400', (await req('PATCH', '/admin/instance', { imprintUrl: 'javascript:alert(1)' })).status === 400);
await req('PATCH', '/admin/instance', { imprintUrl: 'https://example.org/imprint' });
check('imprint in status', (await req('GET', '/status')).data.imprintUrl === 'https://example.org/imprint');
await req('PATCH', '/admin/instance', { imprintUrl: '' });
check('operator bad email 400', (await req('PATCH', '/admin/instance', { operator: { name: 'Erika Muster', email: 'kein-mail' } })).status === 400);
await req('PATCH', '/admin/instance', { operator: { name: 'Erika Muster', street: 'Musterweg 1', city: '12345 Musterstadt', email: 'erika@example.org', junk: 'x' } });
const legal = await (await fetch('http://localhost:3999/api/legal')).json();
check('legal public + sanitized', legal.operator.name === 'Erika Muster' && legal.operator.city === '12345 Musterstadt' && !('junk' in legal.operator), JSON.stringify(legal));
check('status hasOperator', (await req('GET', '/status')).data.hasOperator === true);
s = (await req('GET', '/stats')).data;
check('all years perYear', s.year === null && s.perYear.length >= 1);
check('bad year 400', (await req('GET', '/stats?year=20x4')).status === 400);
// Scan eines importierten Buchs ohne Exemplar: Lesestand + Datum bleiben erhalten
const mb = (await req('POST', '/books', { title: 'Importiert ohne Exemplar', authors: ['Testerin'] })).data;
await req('PUT', `/books/${mb.id}/reading`, { status: 'read', finishedAt: '2023-05-01' });
await req('POST', '/copies', { bookId: mb.id, format: 'print', binding: 'paperback', readStatus: 'read' });
const mr = (await req('GET', `/books/${mb.id}`)).data;
check('scan keeps imported reading', mr.reading.status === 'read' && mr.reading.finishedAt === '2023-05-01' && mr.copies.some(c => c.mine), JSON.stringify(mr.reading));
console.log(`Statistik-Test: ${ok} ok, ${fail} fehlgeschlagen`);
